# Generated by Django 3.2 on 2024-03-27 05:40

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('management', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='PlantedStatus',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100)),
            ],
        ),
        migrations.AlterModelOptions(
            name='geolocation',
            options={'ordering': ['-date_time']},
        ),
        migrations.AddField(
            model_name='lot',
            name='section',
            field=models.ForeignKey(default=1, on_delete=django.db.models.deletion.CASCADE, to='management.section'),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='geolocation',
            name='status',
            field=models.ForeignKey(default=1, on_delete=django.db.models.deletion.PROTECT, to='management.plantedstatus'),
            preserve_default=False,
        ),
    ]
